[book]
authors = ["Michael Currin"]
language = "en"
multilingual = false
src = "src"
title = "Beilong Tang (DKU)"
description = "Demo site for mdBook Quickstart repo"

[output.html]
mathjax-support = true
