name: Rust CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: rust-lang/simpleinfra/github-actions/simple-ci@master
        with:
          check_fmt: true

      - name: Install dependencies 🔧
        run: make install

      - name: Build 🏗️
        run: make build

      - name: Deploy to GitHub Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book
